config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mains#landing', as: 'landing'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/activate', to: 'users#activate', as: 'activate'
  put '/activate', to: 'users#activated', as: 'activated'
  put '/regerate', to: 'users#regenerate_code', as: 'regenerate_code'

  put '/courses/:course_id/enroll', to: 'courses#enroll', as: 'course_enroll'
  put '/courses/:course_id/posts/:post_id/award', to: 'posts#award', as: 'course_post_award'
  put '/courses/:course_id/posts/:post_id/comments/:comment_id/award', to: 'comments#award', as: 'course_post_comment_award'

  resources :sessions, only: [:create]
  resources :users, except: [:new]

  resources :courses do
    resources :posts do
      resources :comments
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates_presence_of :first_name, :last_name

    has_many :enrollment, dependent: :destroy
    has_many :courses, through: :enrollment

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :awards, dependent: :destroy

    before_save :generate_register_code

    enum role: %w[student tutor lecturer admin]

    def activate
        self.activated = true
        self.save
    end

    def deactivate
        self.activated = false
        self.save
    end

    def generate_register_code
        code = ""
        6.times do
            code += rand(0..9).to_s
        end
        self.register_code = code
    end

    def regenerate_regsiter_code
        self.generate_register_code
        self.save
    end

    def has_award(backer, post, comment)
        if Award.find_by(user: self, backer: backer, post: post, comment: comment).nil?
            return false
        else
            return true
        end
    end

    def get_award(backer, post, comment)
        award = Award.new
        award.user = self
        award.backer = backer
        award.post = post
        award.comment = comment
        if backer.role_before_type_cast != 0
          award.award_type = 1
        end
        award.save
    end

    def toggle_reward(backer, post, comment)
        award = Award.find_by(user: self, backer: backer, post: post, comment: comment)
        if award.nil?
            self.get_award(backer, post, comment)
        else
            award.destroy
        end
    end

    def full_name_to_s
        return "#{self.first_name} #{self.last_name}"
    end

    def awards_to_s
        awards = self.awards.all
        return "Trophies : #{awards.where(award_type: 1).count} | Medals: #{awards.where(award_type: 0).count}"
    end

    def trophies_to_s
        return "Trophies : #{self.awards.where(award_type: 1).count}"
    end

    def medals_to_s
        return "Medals : #{self.awards.where(award_type: 0).count}"
    end

    def to_s
        return "#{self.full_name_to_s} (#{self.awards_to_s})"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :logged_in?, only: %i[index show edit update destory]

    before_action :sessioned?, only: %i[new create]

    before_action :set_user, only: %i[show edit update destroy]
    before_action :correct_user?, only: %i[show edit update destory]


    def show
    end
  
    def index
        @users = User.all
    end
  
    def new
      @user = User.new
    end

    def activate
    end

    def activated
        if params[:code] == current_user.register_code
            current_user.activate
            flash[:success] = "true"
            flash[:message] = "Account successfully activated"
            redirect_to user_path(current_user.id)
        else
            flash[:success] = "false"
            flash[:message] = "Incorrect 6-digit code"
            redirect_to activate_path
        end
    end

    def regenerate_code
        current_user.regenerate_regsiter_code
        redirect_to activate_path
    end
  
    def create
        @user = User.create(user_params)

        if @user.valid?
            
            session[:user_id] = @user.id
            flash[:success] = "true"
            flash[:message] = "Successfully created an account."
            redirect_to "/"
        else
            flash[:success] = "false"
            flash[:message] = "An error occured while creating an account. Please try again."
            flash[:errors] = @user.errors
            redirect_to register_path
        end
    end
  
    private 
    def set_user
        if params[:id]
          @user = User.find(params[:id])
        else
          @user = User.find(params[:user_id])
        end
      end
    
    def user_params
        params.require(:user).permit(
          :email,
          :first_name,
          :last_name,
          :password,
          :password_confirmation
        )
    end
  
    def correct_user?
        not_found unless current_user == @user or current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.haml
%h3 Your Account
.card
  .card-header  
    .row
      .col-2.fw-bold
        First Name
      .col
        = user.first_name
  .card-header  
    .row
      .col-2.fw-bold
        Last Name
      .col
        = user.last_name
  .card-header  
    .row
      .col-2.fw-bold
        Email
      .col
        = user.email
%br/
%h3 Enrolled Courses
%ul.list-group
  - user.enrollment.each do |enrollment|
    %li.list-group-item
      = render enrollment.course

%br/
%h3 Awards
.card
  .card-header  
    .row
      .col.fw-bold
        = user.trophies_to_s
      .col.fw-bold
        = user.medals_to_s
%ul.list-group
  - user.awards.each do |award|
    %li.list-group-item
      - if !award.post.nil?
        #{link_to award.to_s, course_post_path(award.post.course, award.post), method: :get, :class => "text-decoration-none"}
      - elsif !award.comment.nil?
        #{link_to award.to_s, course_post_path(award.comment.post.course, award.comment.post), method: :get, :class => "text-decoration-none"}
      - else
        = award.to_s

app/views/users/activate.haml
= form_with url: activated_path, method: :put do |form|
  .modal-dialog
    .modal-content
      .modal-header.text-center
        %h4.modal-title.w-100.font-weight-bold
          = form.label(:query, "Enter your 6-digit code")
      #c_form-h.m-3
        .form-group.row
          %label.col-2.col-form-label Code
          .col-10
            = form.text_field(:code, class:"form-control", placeholder:"The  6-digit code is sent to your email")
      .modal-footer
        = form.submit("Activate", class:"btn btn-default modal-title w-100 font-weight-bold")

.modal-dialog
  .modal-content
    .nav
      .col.btn.text-decoration-none
        Don't see your code?
      .col
        #{button_to "Resend Code", regenerate_code_path, method: :put, :class => "btn w-100 text-primary"}
= current_user.register_code

app/views/users/index.haml
%h1 Index page
- @users.each do |user|
  = user.email
  %br/
  %br/

app/views/users/new.haml
= form_with(model: @user, local: true) do |form|
  .modal-dialog{:role => "document"}
    .modal-content{:style => ""}
      .modal-header.text-center
        %h4.modal-title.w-100.font-weight-bold Register
      #c_form-h.m-3
        .form-group.row
          %label.col-2.col-form-label.fw-bold E-mail
          .col-10
            = form.text_field :email, class:"form-control", id:"inputmailh", placeholder:"mail@example.com"
        %br/
        .form-group.row
          %label.col-2.col-form-label.fw-bold Password
          .col-10
            = form.password_field :password, class:"form-control", id:"inputpasswordh", placeholder:"Password"
        %br/
        .form-group.row
          %label.col-2.col-form-label Confirm
          .col-10
            = form.password_field :password_confirmation, class:"form-control", id:"inputpasswordh", placeholder:"Re-type your Password"
        %hr/
        .row
          .col-sm.fw-bold
            First Name
          .col-sm.fw-bold
            Last Name
        .row
          .col-sm
            = form.text_field :first_name, class:"form-control", placeholder:"Name"
          .col-sm
            = form.text_field :last_name, class:"form-control", placeholder:"Surname"
        %br/
      .modal-footer.d-flex.justify-content-center
        = form.submit "Submit", class:"btn btn-default modal-title w-100 font-weight-bold"

app/views/users/show.haml
= render @user