config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mains#landing', as: 'landing'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/activate', to: 'users#activate', as: 'activate'
  put '/activate', to: 'users#activated', as: 'activated'
  put '/regerate', to: 'users#regenerate_code', as: 'regenerate_code'

  put '/courses/:course_id/enroll', to: 'courses#enroll', as: 'course_enroll'
  put '/courses/:course_id/posts/:post_id/award', to: 'posts#award', as: 'course_post_award'
  put '/courses/:course_id/posts/:post_id/comments/:comment_id/award', to: 'comments#award', as: 'course_post_comment_award'

  resources :sessions, only: [:create]
  resources :users, except: [:new]

  resources :courses do
    resources :posts do
      resources :comments
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :logged_in?

  before_action :set_course, only: %i[show edit update destroy enroll]
  before_action :get_posts, only: %i[show]

  before_action :is_admin?, only: %i[new edit update destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:success] = "true"
      flash[:message] = "Successfully created a course."
      redirect_to courses_path
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while creating a course. Please try again."
      flash[:errors] = @course.errors
      redirect_to new_course_path
    end
  end

  def update
    if @course.update(course_params)
      flash[:success] = "true"
      flash[:message] = "Successfully edited the course."
      redirect_back(fallback_location: courses_path)
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while editing the course. Please try again."
      flash[:errors] = @course.errors
      redirect_to edit_course_path
    end
  end

  def destroy
    flash[:message] = "Course has been deleted."
    @course.destroy
    redirect_to courses_url
  end

  def enroll
    @course.toggle_enrollment(current_user)
    redirect_back(fallback_location: course_path(@course))
  end

  private
  def set_course
    if params[:id]
      @course = Course.find(params[:id])
    else
      @course = Course.find(params[:course_id])
    end
  end

    def get_posts
      @posts = @course.posts
    end

    def course_params
      params.require(:course).permit(:code, :name)
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.haml
.card{:style => "width: 20rem;"}
  .card-body
    #{button_to course.to_s, course_path(course), method: :get, :class => "btn btn-link btn-sm text-decoration-none fs-5"}
    #{button_to course.enrollment_bool_to_s(current_user) , course_enroll_path(course), method: :put, :class => "btn btn-link text-decoration-none fw-bold"}

    - if current_user.admin?
      %form(action="javascript:void(0)") 
        %button.form.btn.btn-link.text-decoration-none.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :onclick => "ajax_get_page('GET', '#{edit_course_path(course, :yeild_only => true)}', 'ajax_content')"} Edit
        #{button_to "Delete", course, method: :delete, :class => "btn btn-link text-decoration-none fw-bold"}
- if controller_name == 'courses' and action_name == 'show'
  %hr/
  = render :template => 'posts/index', :locals => {:course_id => course.id}

app/views/courses/_form.haml
= form_with(model: course) do |form|
  .modal-dialog
    .modal-content
      .modal-header.text-center
        %h4.modal-title.w-100.font-weight-bold #{action_name.capitalize} Course
      #c_form-h.m-3
        .form-group.row
          %label.col-2.col-form-label.fw-bold Code
          .col-10
            = form.text_field :code, class:"form-control", placeholder:"Course Code"
        %br/
        .form-group.row
          %label.col-2.col-form-label.fw-bold Name
          .col-10
            = form.text_field :name, class:"form-control", placeholder:"Course Name"
      .modal-footer.d-flex.justify-content-center
        = submit_tag "Submit", class:"btn btn-default modal-title w-100 font-weight-bold"

app/views/courses/edit.haml
= render "form", course: @course

app/views/courses/index.haml
.nav
  .col
    .d-flex.float-start
      %h3 All Courses
  .col
    - if current_user.admin?
      .d-flex.float-end
        %button.btn.btn-primary.fs-6.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_path(:yeild_only => true)}', 'ajax_content')"} New Course
%br/
.container 
  .row
    - @courses.each do |course|
      = render course

app/views/courses/new.haml
= render "form", course: @course

app/views/courses/show.haml
= render @course