config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mains#landing', as: 'landing'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/activate', to: 'users#activate', as: 'activate'
  put '/activate', to: 'users#activated', as: 'activated'
  put '/regerate', to: 'users#regenerate_code', as: 'regenerate_code'

  put '/courses/:course_id/enroll', to: 'courses#enroll', as: 'course_enroll'
  put '/courses/:course_id/posts/:post_id/award', to: 'posts#award', as: 'course_post_award'
  put '/courses/:course_id/posts/:post_id/comments/:comment_id/award', to: 'comments#award', as: 'course_post_comment_award'

  resources :sessions, only: [:create]
  resources :users, except: [:new]

  resources :courses do
    resources :posts do
      resources :comments
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body

    belongs_to :course
    belongs_to :user

    has_many :comments, dependent: :destroy
    has_many :awards, dependent: :destroy

    def awards_to_s
        return "Trophies: #{self.awards.where(award_type: 1).count} | Medals: #{self.awards.where(award_type: 0).count}"
    end

    def award_bool_to_s(user)
        if self.awards.find_by(backer: user).nil?
            return "Reward"
        else
            return "Unreward"
        end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in?

  before_action :get_course
  before_action :set_post, only: %i[show edit update destroy award]

  before_action :can_modify?, only: %i[edit update]
  before_action :can_delete?, only: %i[destroy]

  before_action :awardable?, only: %i[award]

  def index
    @posts = @course.posts
  end

  def show
  end

  def new
    @post = @course.posts.build
  end

  def edit
  end

  def create
    @post = @course.posts.build(post_params)
    @post.user = current_user

    if @post.save
      flash[:success] = "true"
      flash[:message] = "Successfully created a post."
      redirect_to course_path(@course)
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while creating a course. Please try again."
      flash[:errors] = @post.errors
      redirect_to new_course_post_path
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "true"
      flash[:message] = "Successfully updated the post."
      redirect_back(fallback_location: course_path(@course))
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while editing the post. Please try again."
      flash[:errors] = @post.errors
      redirect_to edit_course_posts_path
    end
  end

  def destroy
    flash[:message] = "Post has been deleted."
    @post.destroy
    redirect_to course_path(@course)
  end

  def award
    @post.user.toggle_reward(current_user, @post, nil)
    redirect_back(fallback_location: course_path(@course))
  end

  private
    def set_post
      if params[:id]
        @post = @course.posts.find(params[:id])
      else
        @post = @course.posts.find(params[:post_id])
      end
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def get_course
      @course = Course.find(params[:course_id])
    end

    def can_modify?
      not_found unless @post.user == current_user
    end

    def can_delete?
      not_found unless @post.user == current_user or !current_user.student?
    end

    def awardable?
      redirect_back(fallback_location: course_path(@course)) if @post.user == current_user
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.haml
= form_with(model: [@course, post]) do |form|
  .modal-dialog
    .modal-content
      .modal-header.text-center
        %h4.modal-title.w-100.font-weight-bold #{action_name.capitalize} Post
      #c_form-h.m-3
        .form-group.row
          %label.col-2.col-form-label.fw-bold Title
          .col-10
            = form.text_field :title, class:"form-control", placeholder:"Post Title"
        %hr/
        .row
          .col-sm.fw-bold
            Descrtiption
        %br/
        .row
          .col-sm
            = form.text_area :body, class:"form-control", rows:"15", placeholder:"Enter your post description..."
      .modal-footer.d-flex.justify-content-center
        = submit_tag "Submit", class:"btn btn-default modal-title w-100 font-weight-bold"

app/views/posts/_post.haml
.card
  .card-header
    .nav
      .col
        .d-flex.float-start
          #{link_to post.title, course_post_path(@course, post), method: :get, :class => "text-decoration-none fs-4"}
      .col
        .d-flex.float-end
          
  .card-body
    = post.body
  .card-footer.text-muted
    .nav
      .col
        
      .col
        .d-flex.float-end
          - if post.user == current_user
            %form(action="javascript:void(0)") 
              %button.form.btn.btn-link.btn-sm.text-decoration-none.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :onclick => "ajax_get_page('GET', '#{edit_course_post_path(@course, post, :yeild_only => true)}', 'ajax_content')"} Edit
          - if post.user == current_user or !current_user.student?
            #{button_to "Delete", [@course, post], method: :delete, :class => "btn btn-link btn-sm text-decoration-none fw-bold"}

app/views/posts/edit.haml
= render "form", post: @post

app/views/posts/index.haml
🏛️ 150 students enrolled
%br/
🟢 10 students online
%br/
%hr/
🧑‍🤝‍🧑 5 in your group
%br/
🟢 2 online (including you)
%hr/
.nav
  .col
    .d-flex.float-start
      %h3 All Topics
  .col 
    .d-flex.float-end
      - if defined? course_id
        %button.btn.btn-primary.fs-6.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_post_path(:course_id => course_id ,:yeild_only => true)}', 'ajax_content')"} New Topic
      - else
        %button.btn.btn-primary.fs-6.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_post_path(:yeild_only => true)}', 'ajax_content')"} New Topic
.h6 📖 0/2 projects complete
%br/
- @posts.each do |post|
  = render post
  %br/

%hr/
.nav
  .col
    .d-flex.float-start
      %h3 Group Assignments
%br/
.h6 No assignments yet

app/views/posts/new.haml
= render "form", post: @post

app/views/posts/show.haml
#{link_to "< Back to course page", course_path(@post.course), method: :get, :class => "text-decoration-none fs-6"}
%br/
%br/
= render @post
%br/
.container
  .h3
    Voice Channel
  🔈🎤 Adrian Low
  %br/
  🔇❌ Alan Turing
  %br/
  🔈🎤
  = current_user.full_name_to_s

.py-5
  .container
    .row
      .col-md-10
        %iframe{:height => "500px", :src => "https://www.online-python.com/online_python_compiler", :width => "1000px"}

%br/
- if controller_name == 'posts' and action_name == 'show'
  = render :template => 'comments/index', :locals => {:course_id => @post.course.id, :post_id => @post.id}