config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mains#landing', as: 'landing'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/activate', to: 'users#activate', as: 'activate'
  put '/activate', to: 'users#activated', as: 'activated'
  put '/regerate', to: 'users#regenerate_code', as: 'regenerate_code'

  put '/courses/:course_id/enroll', to: 'courses#enroll', as: 'course_enroll'
  put '/courses/:course_id/posts/:post_id/award', to: 'posts#award', as: 'course_post_award'
  put '/courses/:course_id/posts/:post_id/comments/:comment_id/award', to: 'comments#award', as: 'course_post_comment_award'

  resources :sessions, only: [:create]
  resources :users, except: [:new]

  resources :courses do
    resources :posts do
      resources :comments
    end
  end

end

app/views/layouts/_ajax_popup.haml
#ajax_popup.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "ajax_popup_label", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    #ajax_content
= javascript_include_tag :ajax_get_page

app/views/layouts/_nav.haml
.nav.navbar.navbar-expand-md.navbar-dark.bg-dark.container-fluid
  .col
    .d-flex.float-start
      #{button_to ">_ Co-Code", landing_path, method: :get, :class => "navbar-brand button btn"}
  .col
    .d-flex.float-end
      - if current_user.nil?
        - unless current_page?(register_path)
          %button.btn.nav-link.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{register_path(:yeild_only => true)}', 'ajax_content')"} Register
        - unless current_page?(login_path)
          %button.btn.nav-link.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{login_path(:yeild_only => true)}', 'ajax_content')"} Login
      - else
        #{button_to "Courses", courses_path, method: :get, :class => "button btn nav-link fw-bold"}
        #{button_to "Account", user_path(current_user.id), method: :get, :class => "button btn nav-link fw-bold"}
        #{button_to "Logout", logout_path, method: :delete, :class => "button btn nav-link fw-bold"}

app/views/layouts/_notice.haml
- if flash[:message]
  - if flash[:success] == 'true'
    #alert_bar.alert.alert-success{:role => "alert"}
      = render 'layouts/notice_elements'
  - elsif flash[:success] == 'false'
    #alert_bar.alert.alert-danger{:role => "alert"}
      = render 'layouts/notice_elements'
  - else
    #alert_bar.alert.alert-warning{:role => "alert"}
      = render 'layouts/notice_elements'
  = javascript_include_tag :delete_element

app/views/layouts/_notice_elements.haml
%nav.navbar.navbar-inverse
  .container-fluid.fw-bold
    = flash[:message]
    %ul.nav.navbar-nav.navbar-right
      %li
        %button.btn-close{"aria-label" => "Close", :onclick => "delete_emement_by_id('alert_bar')", :type => "button"}
  .container-fluid 
    - if flash[:errors]
      %ul
        - flash[:errors].each do |error|
          %li
            = error[0].capitalize.gsub("_", " ")
            = error[1][0]

app/views/layouts/application.haml
!!!
%html
  %body
    - if params[:yeild_only] == "true"
      = yield
    - else
      %title DECO3500 Demo
      %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag "application", "data-turbo-track": "reload"
      = render "layouts/nav"
      = render "layouts/notice"
      %div.container.p-4
        = yield
      - if action_name == "index" or action_name == "show" or action_name == "landing"
        = render "layouts/ajax_popup"
      = javascript_include_tag :bootstrap